#!/bin/bash
source /home/catkin_ws/devel/setup.bash
set -e
set -x

#cd ~/turtle
echo "Starting Turtle"
python3 /home/turtle/webstreaming.py &
# echo "Webserver started"
python3 /home/turtle/TurtleMain.py

